image: php:7.1.3
pipelines:
  default:
    - step:
        name: Build
        script:
          - apt-get update && apt-get install -y curl zip unzip
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          - aws --version
          - aws configure set aws_access_key_id "${AWS_KEY}"
          - aws configure set aws_secret_access_key "${AWS_SECRET}"
          - aws=$(aws ecr get-login-password --region ca-central-1)
          - echo $aws | docker login --username AWS --password-stdin 754569496111.dkr.ecr.ca-central-1.amazonaws.com
          - echo "aws=$aws" > ENVIRONMENT_VARIABLES.txt
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build --memory=3072M -t lineblocs-k8s-runner .
          - docker tag lineblocs-k8s-runner:latest 754569496111.dkr.ecr.ca-central-1.amazonaws.com/lineblocs-k8s-runner:latest
          - docker push 754569496111.dkr.ecr.ca-central-1.amazonaws.com/lineblocs-k8s-runner:latest
        services:
          - docker